version: 2

seeds:

  - name: store
    description: Contains data about stores, physical locations where cistomers' business happens. Those stores are classified by different typology.
    meta:
      owner: "@tanya.ivananova"
    config:
      columns:
        - name: id
          description: Unique store identifier 
        - name: name
          description: Store name
        - name: address
          description: Store's address
      column_types:
        id: int
        name: varchar(128)
        address: varchar(256)
        city: varchar(128)
        country: varchar(128)
        created_at: timestamp_ntz
        typology: varchar(128)
        customer_id: int

  - name: device
    description: Contains data about devices (1 to 5). Devices are hardware needed to perform any kind of transactions, each of them are tied up to a specific store.
    meta:
      owner: "@tanya.ivananova"
    config:
      columns:
        - name: id
          description: Unique device identifier 
        - name: type
          description: Device's type (1-5)
        - name: store
          description: Unique store identifier  
  
  - name: transaction
    description: Contains data about transactions. Transaction is a payment made using the provided devices.
    meta:
      owner: "@tanya.ivananova"
    config:
      columns:
        - name: id
          description: Unique transaction identifier 
        - name: device_id
          description: Uniqe device identifier
        - name: product_name
          description: Uniqe product name