
version: 2

models:
  - name: fact_transaction
    description: "Contains data about all transactions"
    columns:
    - name: transaction_id
      description: "The primary key for this table"
      tests:
        - unique
        - not_null
